apply plugin: 'maven-publish'

tasks.register('dokkaJavadocJar', Jar) {
    dependsOn 'dokkaGeneratePublicationJavadoc'   // v2 task
    archiveClassifier.set('javadoc')
    from(layout.buildDirectory.dir('dokka/javadoc'))
}

afterEvaluate {
    publishing {
        publications {
            // Creates a Maven publication called "release".
            release(MavenPublication) {
                from components.release
                groupId project.properties['groupId']
                artifactId project.properties['artifactId']
                version project.properties['versionName']
                artifact tasks.named('dokkaJavadocJar')
            }
        }
    }
}